# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Sistema de Livros - CRUD Completo

livros = []
proximo_id = 1

def cadastrar_livro():
    global proximo_id
    print("\n--- CADASTRAR LIVRO ---")
    titulo = input("Título: ").strip()
    autor = input("Autor: ").strip()
    disponivel = input("Disponível? (s/n): ").lower().strip()

    if titulo == "" or autor == "":
        print("Erro: título e autor não podem ficar vazios.")
        return

    livro = {
        "id": proximo_id,
        "titulo": titulo,
        "autor": autor,
        "disponivel": disponivel == "s"
    }

    livros.append(livro)
    proximo_id += 1
    print("Livro cadastrado com sucesso!")


def listar_livros():
    print("\n--- LISTA DE LIVROS ---")
    if not livros:
        print("Nenhum livro cadastrado.")
        return

    for livro in livros:
        status = "Disponível" if livro["disponivel"] else "Indisponível"
        print(f"ID: {livro['id']} | {livro['titulo']} - {livro['autor']} ({status})")


def atualizar_livro():
    print("\n--- ATUALIZAR LIVRO ---")
    try:
        id_busca = int(input("Informe o ID do livro: "))
    except ValueError:
        print("ID inválido.")
        return

    for livro in livros:
        if livro["id"] == id_busca:
            print(f"Editando: {livro['titulo']} - {livro['autor']}")

            novo_titulo = input("Novo título (Enter para manter): ").strip()
            novo_autor = input("Novo autor (Enter para manter): ").strip()
            novo_status = input("Disponível? (s/n ou Enter p/ manter): ").strip().lower()

            if novo_titulo != "":
                livro["titulo"] = novo_titulo
            if novo_autor != "":
                livro["autor"] = novo_autor
            if novo_status in ["s", "n"]:
                livro["disponivel"] = novo_status == "s"

            print("Livro atualizado!")
            return

    print("Livro não encontrado.")


def remover_livro():
    print("\n--- REMOVER LIVRO ---")
    try:
        id_busca = int(input("Informe o ID do livro: "))
    except ValueError:
        print("ID inválido.")
        return

    for livro in livros:
        if livro["id"] == id_busca:
            livros.remove(livro)
            print("Livro removido com sucesso!")
            return

    print("Livro não encontrado.")


def gerar_relatorio():
    print("\n--- RELATÓRIO ---")
    total = len(livros)
    disponiveis = sum(1 for l in livros if l["disponivel"])

    print(f"Total de livros cadastrados: {total}")
    print(f"Livros disponíveis: {disponiveis}")
    print(f"Livros emprestados: {total - disponiveis}")


def menu():
    while True:
        print("\n===== SISTEMA DE LIVROS =====")
        print("1 - Cadastrar livro")
        print("2 - Listar livros")
        print("3 - Atualizar livro")
        print("4 - Remover livro")
        print("5 - Relatório")
        print("6 - Sair")

        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            cadastrar_livro()
        elif opcao == "2":
            listar_livros()
        elif opcao == "3":
            atualizar_livro()
        elif opcao == "4":
            remover_livro()
        elif opcao == "5":
            gerar_relatorio()
        elif opcao == "6":
            print("Encerrando o sistema...")
            break
        else:
            print("Opção inválida. Tente novamente.")



menu()